name: SutilOxide Publish Pages
on: [workflow_dispatch]
jobs:
  Sutil-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Clean
        run: |
          cd ${{ github.workspace }}
          dotnet clean src/SutilOxide && dotnet nuget locals all --clear
          dotnet clean src/App && dotnet nuget locals all --clear
      - name: Publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY_SECRET }}
        run: |
          cd ${{ github.workspace }}
          npm install
          npm run build
          npm run publish
